### Array Creation and Manipulation

In [1]:
#Q1.1: Create a 4x4 identity matrix using np.eye()
import numpy as np
identity_matrix=np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
#Q1.2: Create an array of 8 zeros using np.zeros()
array_zeros = np.zeros(8)
print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#Q1.3: Create an array of 6 ones using np.ones()
array_ones = np.ones(6)
print(array_ones)

[1. 1. 1. 1. 1. 1.]


In [4]:
#Q1.4: Create an array with values from 0 to 15 using np.arange()
range_array = np.arange(16)
print(range_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [5]:
#Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
linespace_array = np.linspace(0,100,8)
print(linespace_array)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


### Array Attributes and Information

In [6]:
import numpy as np
#[Customer_ID,Account_Balance,Credit_Score,Transaction_Count,Years_Active]
banking_data = np.array([[ 1, 25000, 300, 1200, 10],
    [2, 12000, 450, 150, 5],
    [3, 28000, 380, 46, 8],
    [4, 41000, 500, 160, 18],
    [5, 35000, 420, 400, 12],
    [6, 27000, 360, 30, 9],
    [7, 39000, 480, 700, 18],
    [8, 30000, 400, 250, 14],
    [9, 45000, 420, 800, 20],
    [10, 23000, 410, 45, 9]])

print(banking_data)

[[    1 25000   300  1200    10]
 [    2 12000   450   150     5]
 [    3 28000   380    46     8]
 [    4 41000   500   160    18]
 [    5 35000   420   400    12]
 [    6 27000   360    30     9]
 [    7 39000   480   700    18]
 [    8 30000   400   250    14]
 [    9 45000   420   800    20]
 [   10 23000   410    45     9]]


In [7]:
#Q2.1: What is the shape of the banking_data array?
print(f"shape: {banking_data.shape}")

shape: (10, 5)


In [8]:
#Q2.2: What is the data type of the banking_data array?
print(f"data type: {banking_data.dtype}")

data type: int64


In [9]:
#Q2.3: What is the size (total number of elements) of the banking_data array?
print(f"size: {banking_data.size}")

size: 50


In [10]:
#Q2.4: What is the number of dimensions of the banking_data array?
print(f"dim: {banking_data.ndim}")

dim: 2


In [11]:
#Q2.5: What is the memory size of the banking_data array in bytes?
print(f"bytes: {banking_data.nbytes}")

bytes: 400


### Indexing and Slicing

In [12]:
#Q3.1: Extract the first row of banking_data
first_row = banking_data[0]
print(first_row)

[    1 25000   300  1200    10]


In [13]:
#Q3.2: Extract the last row of banking_data
last_row = banking_data[-1]
print(last_row)

[   10 23000   410    45     9]


In [14]:
#Q3.3: Extract the Account_Balance column (column index 1)
column_index = banking_data[:,1]
print(column_index)

[25000 12000 28000 41000 35000 27000 39000 30000 45000 23000]


In [15]:
#Q3.4: Extract the first 4 rows and first 3 columns
subset = banking_data[:4, :3]
print(subset)

[[    1 25000   300]
 [    2 12000   450]
 [    3 28000   380]
 [    4 41000   500]]


In [16]:
#Q3.5: Extract rows 3 to 7 (inclusive)
rows_3_to_7 = banking_data[3:7]
print(rows_3_to_7)

[[    4 41000   500   160    18]
 [    5 35000   420   400    12]
 [    6 27000   360    30     9]
 [    7 39000   480   700    18]]


### Mathematical Operations

In [17]:
#Q4.1: Calculate the sum of all account balances
total_balance = np.sum(banking_data[:,1])
print(f"Total balance : {total_balance}")

Total balance : 305000


In [18]:
#Q4.2: Calculate the mean account 
mean_account = np.mean(banking_data[:,1])
print(f"Mean account : {mean_account}")

Mean account : 30500.0


In [19]:
#Q4.3: Calculate the standard deviation of account balances
std_balance = np.std(banking_data[:,1])
print(f"standard deviation of account: {std_balance}")

standard deviation of account: 9276.313923105448


In [20]:
#Q4.4: Calculate the variance of account balances
var_balance = np.var(banking_data[:,1])
print(f"variance of account: { var_balance}")

variance of account: 86050000.0


In [21]:
#Q4.5: Calculate the median account balance
med_balance = np.median(banking_data[:,1])
print(f"median account : {med_balance}")

median account : 29000.0


### Statistical Functions

In [22]:
#Q5.1: Find the minimum and maximum account balances
min_balance = np.min(banking_data[:,1])
max_balance = np.max(banking_data[:,1])
print(f"minimum : {min_balance}")
print(f"maximum : {max_balance}")

minimum : 12000
maximum : 45000


In [23]:
#Q5.2: Find the minimum and maximum credit scores
min_scores = np.min(banking_data[:,2])
max_scores = np.max(banking_data[:,2])
print(f"minimum credit : {min_scores}")
print(f"maximum credit : {max_scores}")

minimum credit : 300
maximum credit : 500


In [24]:
#Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
percentile = np.percentile(banking_data[:,1],[25,50,75])
print(f"+25th percentile : {percentile[0]}")
print(f"+50th percentile : {percentile[1]}")
print(f"+75th percentile : {percentile[2]}")


+25th percentile : 25500.0
+50th percentile : 29000.0
+75th percentile : 38000.0


In [25]:
#Q5.4: Calculate the correlation between account balance and credit score
correlation = np.corrcoef(banking_data[:,1],banking_data[:,3])[0,1]
print(f"correlation :{correlation}")

correlation :0.31433420336741874


In [26]:
#Q5.5: Calculate the covariance between account balance and credit score
covariance = np.cov(banking_data[:,1],banking_data[:,3])[0,1]
print(f"covariance :{covariance}")

covariance :1219166.6666666665


###  Array Reshaping and Manipulation

In [27]:
#Q6.1: Reshape the banking_data to 5 rows × 10 columns
reshaped_5x10 = banking_data.reshape(5,10)
print(reshaped_5x10)

[[    1 25000   300  1200    10     2 12000   450   150     5]
 [    3 28000   380    46     8     4 41000   500   160    18]
 [    5 35000   420   400    12     6 27000   360    30     9]
 [    7 39000   480   700    18     8 30000   400   250    14]
 [    9 45000   420   800    20    10 23000   410    45     9]]


In [28]:
#Q6.2: Flatten the banking_data to a 1D array
flattend = banking_data.flatten()
print(flattend)

[    1 25000   300  1200    10     2 12000   450   150     5     3 28000
   380    46     8     4 41000   500   160    18     5 35000   420   400
    12     6 27000   360    30     9     7 39000   480   700    18     8
 30000   400   250    14     9 45000   420   800    20    10 23000   410
    45     9]


In [29]:
#Q6.3: Transpose the banking_data
transpose = banking_data.transpose()
print(transpose)

[[    1     2     3     4     5     6     7     8     9    10]
 [25000 12000 28000 41000 35000 27000 39000 30000 45000 23000]
 [  300   450   380   500   420   360   480   400   420   410]
 [ 1200   150    46   160   400    30   700   250   800    45]
 [   10     5     8    18    12     9    18    14    20     9]]


In [30]:
#Q6.4: Split the banking_data into 2 equal parts vertically
split_vertical = np.vsplit(banking_data,2)
print(f"first_part: {split_vertical[0]}")
print(f"second_part: {split_vertical[1]}")


first_part: [[    1 25000   300  1200    10]
 [    2 12000   450   150     5]
 [    3 28000   380    46     8]
 [    4 41000   500   160    18]
 [    5 35000   420   400    12]]
second_part: [[    6 27000   360    30     9]
 [    7 39000   480   700    18]
 [    8 30000   400   250    14]
 [    9 45000   420   800    20]
 [   10 23000   410    45     9]]


In [31]:
#Q6.5: Split the banking_data into 2 equal parts horizontally
split_horizontal = np.hsplit(banking_data,2.5)
print(f"first_part: {split_horizontal[0]}")
print(f"second_part: {split_horizontal[1]}")



first_part: [[    1 25000   300]
 [    2 12000   450]
 [    3 28000   380]
 [    4 41000   500]
 [    5 35000   420]
 [    6 27000   360]
 [    7 39000   480]
 [    8 30000   400]
 [    9 45000   420]
 [   10 23000   410]]
second_part: [[1200   10]
 [ 150    5]
 [  46    8]
 [ 160   18]
 [ 400   12]
 [  30    9]
 [ 700   18]
 [ 250   14]
 [ 800   20]
 [  45    9]]


##### Logical Operations and Filtering

In [32]:
#Q7.1: Find customers with account balance greater than $100,000
high_balance_customers = banking_data[:, 1] > 100,000
print(high_balance_customers)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True]), 0)


In [33]:
#Q7.2: Find customers with credit score greater than 800
banking_data[:,2]>800

array([False, False, False, False, False, False, False, False, False,
       False])

In [34]:
#Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
banking_data[(banking_data[:, 3] > 50) & (banking_data[:, 2] < 750)]

array([[    1, 25000,   300,  1200,    10],
       [    2, 12000,   450,   150,     5],
       [    4, 41000,   500,   160,    18],
       [    5, 35000,   420,   400,    12],
       [    7, 39000,   480,   700,    18],
       [    8, 30000,   400,   250,    14],
       [    9, 45000,   420,   800,    20]])

In [35]:
#Q7.4: Count how many customers have account balance between $10,000 and $100,000
data = np.sum((banking_data[:,1] >= 10000) & (banking_data[:,1] <= 100000))
print(data)

10


In [36]:
#Q7.5: Find the index of the customer with the highest credit score
customer = np.argmax(banking_data[:, 2])+1
print(customer)

4


### Sorting and Searching

In [37]:
#Q8.1: Sort the banking_data by account balance (ascending)
sorted_by_account = banking_data[banking_data[:,1].argsort()]
sorted_by_account

array([[    2, 12000,   450,   150,     5],
       [   10, 23000,   410,    45,     9],
       [    1, 25000,   300,  1200,    10],
       [    6, 27000,   360,    30,     9],
       [    3, 28000,   380,    46,     8],
       [    8, 30000,   400,   250,    14],
       [    5, 35000,   420,   400,    12],
       [    7, 39000,   480,   700,    18],
       [    4, 41000,   500,   160,    18],
       [    9, 45000,   420,   800,    20]])

In [38]:
#Q8.2: Sort the banking_data by credit score (descending)
data = banking_data[np.argsort(banking_data[:,3])[::-1]]
print(data)

[[    1 25000   300  1200    10]
 [    9 45000   420   800    20]
 [    7 39000   480   700    18]
 [    5 35000   420   400    12]
 [    8 30000   400   250    14]
 [    4 41000   500   160    18]
 [    2 12000   450   150     5]
 [    3 28000   380    46     8]
 [   10 23000   410    45     9]
 [    6 27000   360    30     9]]


In [39]:
#Q8.3: Find the indices that would sort the array by years active
active_indices = np.argsort(banking_data[:,4])
print(active_indices)

[1 2 5 9 0 4 7 3 6 8]


In [40]:
#Q8.4: Find the customer with the second highest account balance
second_highest_account = np.argsort(banking_data[:,1])[-2]
second_highest_account = banking_data[second_highest_account]
print(f"Customer ID: {int(second_highest_account[0])}, Account Balance: {int(second_highest_account[1])}")

Customer ID: 4, Account Balance: 41000


In [41]:
#Q8.5: Find the customer with the lowest transaction count
lowest_transaction = np.argmin(banking_data[:, 3])
lowest_transaction = banking_data[lowest_transaction]
print(f"Customer ID: {int(lowest_transaction [0])}, Transaction Count: {int(lowest_transaction [3])}")

Customer ID: 6, Transaction Count: 30


### Mathematical Functions

In [42]:
#Q9.1: Calculate the absolute values of all elements
absolute_values = np.abs(banking_data)
print(absolute_values)

[[    1 25000   300  1200    10]
 [    2 12000   450   150     5]
 [    3 28000   380    46     8]
 [    4 41000   500   160    18]
 [    5 35000   420   400    12]
 [    6 27000   360    30     9]
 [    7 39000   480   700    18]
 [    8 30000   400   250    14]
 [    9 45000   420   800    20]
 [   10 23000   410    45     9]]


In [43]:
#Q9.2: Calculate the square root of all account balances
sqrt_account = np.sqrt(banking_data[:,1])
print(sqrt_account)

[158.11388301 109.5445115  167.33200531 202.48456731 187.08286934
 164.31676725 197.48417658 173.20508076 212.13203436 151.65750888]


In [44]:
#Q9.3: Calculate the square of all credit scores
credit_scores = np.square(banking_data[:,2])
print(credit_scores)

[ 90000 202500 144400 250000 176400 129600 230400 160000 176400 168100]


In [5]:
#Q9.4: Calculate the exponential of all transaction counts
import numpy as np
banking_data = np.array([
    [ 1, 25000, 300, 1200, 10],
    [2, 12000, 450, 150, 5],
    [3, 28000, 380, 46, 8],
    [4, 41000, 500, 160, 18],
    [5, 35000, 420, 400, 12],
    [6, 27000, 360, 30, 9],
    [7, 39000, 480, 700, 18],
    [8, 30000, 400, 250, 14],
    [9, 45000, 420, 800, 20],
    [10, 23000, 410, 45, 9]])

print(banking_data)
np.exp(banking_data[:, 3])

[[    1 25000   300  1200    10]
 [    2 12000   450   150     5]
 [    3 28000   380    46     8]
 [    4 41000   500   160    18]
 [    5 35000   420   400    12]
 [    6 27000   360    30     9]
 [    7 39000   480   700    18]
 [    8 30000   400   250    14]
 [    9 45000   420   800    20]
 [   10 23000   410    45     9]]


C:\Users\admin\AppData\Local\Temp\ipykernel_6236\2203053695.py:16: RuntimeWarning: overflow encountered in exp
  np.exp(banking_data[:, 3])


array([            inf, 1.39370958e+065, 9.49611942e+019, 3.06984964e+069,
       5.22146969e+173, 1.06864746e+013, 1.01423205e+304, 3.74645461e+108,
                   inf, 3.49342711e+019])

In [46]:
#Q9.5: Calculate the natural logarithm of all account balances
logarithm = np.log(banking_data[:, 1])
print(logarithm)

[10.1266311   9.39266193 10.23995979 10.62132735 10.46310334 10.20359214
 10.57131693 10.30895266 10.71441777 10.04324949]


### Advanced Operations

In [47]:
#Q10.1: Calculate the cumulative sum of account balances
cummulative = np.sum(banking_data[:, 1])
print(cummulative)

305000


In [48]:
#Q10.2: Calculate the cumulative product of transaction counts
cumprod_transaction = np.cumprod(banking_data[:,3])
print(cumprod_transaction)

[                1200               180000              8280000
           1324800000         529920000000       15897600000000
    11128320000000000  2782080000000000000 -6392032918855745536
  7506423830844276736]


#Q10.3: Calculate the difference between consecutive account balances
diff_account = np.diff(banking_data[:, 1])
print(diff_account)

In [49]:
#Q10.4: Calculate the gradient of account balances
gradient_account = np.gradient(banking_data[:,1])
print(gradient_account)

[-13000.   1500.  14500.   3500.  -7000.   2000.   1500.   3000.  -3500.
 -22000.]


In [50]:
#Q10.5: Calculate the histogram of account balances with 5 bins
hist_account ,bin_edges = np.histogram(banking_data[:,1], bins=5)
print(f"histogram : {hist_account}")
print(f"bin_edges : {bin_edges}")

histogram : [1 2 3 1 3]
bin_edges : [12000. 18600. 25200. 31800. 38400. 45000.]


### Random Numbers and Simulation

In [51]:
#Q11.1: Generate 6 random integers between 1 and 1000
random_int = np.random.randint(1,1001,6)
print(random_int)

[941 396 778 883 884 732]


In [52]:
#Q11.2: Generate 6 random floats between 0 and 1
random_floats = np.random.random(6)
print(random_floats)

[0.44824327 0.64758382 0.43269545 0.1021279  0.5534456  0.10312104]


In [53]:
#Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100) normal_random = np.random.normal(700,100,6) print(normal_random)
normal_random = np.random.normal(700,100,6)
print(normal_random)

[915.41446851 648.70281519 601.18606543 673.11361091 586.34779393
 805.16599085]


In [54]:
#Q11.4: Shuffle the banking_data rows randomly
shuffled_data = banking_data.copy()
np.random.shuffle(shuffled_data)
print(shuffled_data)

[[    4 41000   500   160    18]
 [    8 30000   400   250    14]
 [   10 23000   410    45     9]
 [    6 27000   360    30     9]
 [    9 45000   420   800    20]
 [    5 35000   420   400    12]
 [    7 39000   480   700    18]
 [    1 25000   300  1200    10]
 [    3 28000   380    46     8]
 [    2 12000   450   150     5]]


In [55]:
#Q11.5: Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
seeded_random = np.random.random(4)
print(seeded_random)

[0.69646919 0.28613933 0.22685145 0.55131477]


### Linear Algebra Operations

In [56]:
#Q12.1: Calculate the dot product of account balance and credit score columns
dot_product = np.dot(banking_data[:, 1],banking_data[:, 2])
print(f"Dot product : {dot_product}")

Dot product : 127510000


In [57]:
#Q12.2: Calculate the cross product of first two rows
cross_product = np.cross(banking_data[0,:3], banking_data[1, :3])
print(cross_product)

[7650000     150  -38000]


In [58]:
#Q12.3: Calculate the norm (magnitude) of the account balance column
account_norm  = np.linalg.norm(banking_data[:,1])
print(account_norm)

100811.70566953026


In [59]:
#Q12.4: Create a 3x3 matrix and calculate its determinant
matrix_3x3 = np.array([ 
    [2, 5, 3],
    [1, -2, 9],
    [3, 6, 2]
])
determinant = np.linalg.det(matrix_3x3)
print(f"Matrix :\n{matrix_3x3}")
print(f"determinant : {determinant}")

Matrix :
[[ 2  5  3]
 [ 1 -2  9]
 [ 3  6  2]]
determinant : 44.99999999999999


In [60]:
#Q12.5: Calculate the inverse of the 3x3 matrix
inverse_matrix = np.linalg.inv(matrix_3x3)
print(inverse_matrix)

[[-1.28888889  0.17777778  1.13333333]
 [ 0.55555556 -0.11111111 -0.33333333]
 [ 0.26666667  0.06666667 -0.2       ]]


### String Operations

In [61]:
#Q13.1: Convert all customer IDs to strings
customer_IDs_str = banking_data[:, 0].astype(str)  #stringarrayusing.astype()
print(customer_IDs_str)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [62]:
#Q13.2: Check if any customer ID contains '100'
customer_100 = np.char.find(customer_IDs_str, '100') >= 0
print(customer_100)

[False False False False False False False False False False]


In [63]:
#Q13.3: Convert all customer IDs to uppercase (if they were strings)
customer_IDs_upper = np.char.upper(customer_IDs_str)
print(customer_IDs_upper)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [64]:
#Q13.4: Count the length of each customer ID string
Id_length = np.char.str_len(customer_IDs_str)
print(Id_length)

[1 1 1 1 1 1 1 1 1 2]


In [65]:
#Q13.5: Replace '100' with 'CUST' in customer IDs
replaced_Ids = np.char.replace(customer_IDs_str, '100', 'CUST')
print(replaced_Ids)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


### Date and Time Operations

In [66]:
    #Q14.1: Convert years active to months
years_active = banking_data[:, 4]*12
print(years_active)

[120  60  96 216 144 108 216 168 240 108]


In [67]:
#Q14.2: Calculate the average years active
average_years = np.mean(banking_data[:,4])
print(f"Average Years: {average_years}")

Average Years: 12.3


In [68]:
#Q14.3: Find customers who have been active for more than 5 years
long_active = banking_data[banking_data[:,4] > 5]
print(long_active)

[[    1 25000   300  1200    10]
 [    3 28000   380    46     8]
 [    4 41000   500   160    18]
 [    5 35000   420   400    12]
 [    6 27000   360    30     9]
 [    7 39000   480   700    18]
 [    8 30000   400   250    14]
 [    9 45000   420   800    20]
 [   10 23000   410    45     9]]


In [69]:
#Q14.4: Calculate the total time all customers have been active (in years)
total_active_time = np.sum(banking_data[:, 4])
print(f" Total Active Time : {total_active_time}")

 Total Active Time : 123


In [70]:
#Q14.5: Find the customer with the shortest time active 

shorest_active_idx = np.argmin(banking_data[:,4])
shorest_active_customer = banking_data[shorest_active_idx]
print(f"customer ID: {shorest_active_customer[0]}, Days: {shorest_active_customer[4]}")


customer ID: 2, Days: 5


### Advanced Array Operations

In [71]:
#Q15.1: Apply a function to calculate 5% interest on all account balances
banking_data[:, 1] = banking_data[:,1]*1.05 #5%=1.05
banking_data[:, 1] = np.round(banking_data[:,1],2)
print(banking_data)

[[    1 26250   300  1200    10]
 [    2 12600   450   150     5]
 [    3 29400   380    46     8]
 [    4 43050   500   160    18]
 [    5 36750   420   400    12]
 [    6 28350   360    30     9]
 [    7 40950   480   700    18]
 [    8 31500   400   250    14]
 [    9 47250   420   800    20]
 [   10 24150   410    45     9]]


In [72]:
#Q15.2: Use np.where to categorize customers by balance ranges
balances = banking_data[:, 1]
categories = np.where(balances < 25000, 'Low',
              np.where(balances < 35000, 'Medium',
              np.where(balances < 45000, 'High', 'Very High')))
print(categories)

['Medium' 'Low' 'Medium' 'High' 'High' 'Medium' 'High' 'Medium'
 'Very High' 'Low']


In [73]:
#Q15.3: Use np.select to categorize customers by credit score ranges
credit_scores = banking_data[:, 2]
conditions = [
    credit_scores < 350,
    (credit_scores >= 350) & (credit_scores < 400),
    (credit_scores >= 400) & (credit_scores < 450),
    credit_scores >= 450
]
chocies = ['poor', 'good', 'fair','Excellent']
score_categories = np.select(conditions, chocies, default='Unknown')
print(score_categories)

['poor' 'Excellent' 'good' 'Excellent' 'fair' 'good' 'Excellent' 'fair'
 'fair' 'fair']


In [6]:
#Q15.4: Use np.piecewise to apply different interest rates based on balance
def low_interest(x): return x * 1.05  
def mid_interest(x): return x * 1.10  
def high_interest(x): return x * 1.20  

interest_prices = np.piecewise(
    banking_data[:, 1],
    [banking_data[:, 1] < 20000, (banking_data[:, 1] >= 20000) & (banking_data[:, 1] < 25000), banking_data[:, 1] >= 25000],
    [low_interest, mid_interest, high_interest]
)
print(interest_prices)

[30000 12600 33600 49200 42000 32400 46800 36000 54000 25300]


In [75]:
#Q15.5: Use np.apply_along_axis to calculate the sum of each row
rows_sums = np.apply_along_axis(np.sum, axis=1, arr=banking_data)
print(rows_sums)

[27761 13207 29837 43732 37587 28755 42155 32172 48499 24624]


### Array Concatenation and Stacking

In [76]:
#Q16.1: Concatenate two arrays horizontally using np.hstack()
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
hstacked = np.hstack([arr1 , arr2])
print(f"Array 1: {arr1}")
print(f"Array 2:  {arr2}")
print(f"Horziontally stacked :{hstacked}")

Array 1: [1 2 3]
Array 2:  [4 5 6]
Horziontally stacked :[1 2 3 4 5 6]


In [77]:
#Q16.2: Concatenate two arrays vertically using np.vstack()
vstacked = np.vstack([arr1 ,arr2])
print(f"Verticalley stacked :{vstacked}")

Verticalley stacked :[[1 2 3]
 [4 5 6]]


In [78]:
#Q16.3: Concatenate arrays along a specific axis using np.concatenate()
concatenate = np.concatenate([arr1 , arr2])
print(f"Concatenate along axis : {concatenate}")

Concatenate along axis : [1 2 3 4 5 6]


In [79]:
#Q16.4: Stack arrays depth-wise using np.dstack()
dstacked = np.dstack([arr1 , arr2])
print(f"Depth-wise stacked :{dstacked}")

Depth-wise stacked :[[[1 4]
  [2 5]
  [3 6]]]


In [80]:
#Q16.5: Create a column stack using np.column_stack()
column_stack = np.column_stack([arr1 , arr2])
print(f"column stack :{column_stack}")

column stack :[[1 4]
 [2 5]
 [3 6]]


### Array Splitting Operations

In [81]:
#Q17.1: Split an array into 3 equal parts using np.split()
arr_split = np.array([1,2,3,4,5,6,7,8,9])
split_parts = np.split(arr_split,3)
print(split_parts)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [82]:
#Q17.2: Split an array at specific indices using np.split()
arr_split = np.array([1,2,3,4,5,6,7,8,9])
split_indices = np.split(arr_split, [3,6])
print(split_indices)                         

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [83]:
#Q17.3: Split an array horizontally using np.hsplit()
arr_split = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])

result = np.hsplit(arr_split, 2)
print(f"Horizontally :\n{result}")


Horizontally :
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [84]:
#Q17.4: Split an array vertically using np.vsplit()
arr_split = np.array([[1, 2, 3, 4],
                       [5, 6, 7, 8]])
split = np.vsplit(arr_split,2)
print(f"Vertically :\n{split}")

Vertically :
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [85]:
#Q17.5: Split an array into equal chunks using np.array_split()
split = np.array([0, 1, 2, 3, 4, 5, 6])
chunks = np.array_split(split , 2)
print(f"Equal chunks :{chunks}")

Equal chunks :[array([0, 1, 2, 3]), array([4, 5, 6])]


### Array Repetition and Tiling

In [86]:
#Q18.1: Repeat each element of an array 3 times using np.repeat()
repeat_elements = np.array([1,2,3,4])
result = np.repeat(repeat_elements,3)
print(result)

[1 1 1 2 2 2 3 3 3 4 4 4]


In [87]:
#Q18.2: Repeat an entire array 2 times using np.tile()
repeat_elements = np.array([1,2,3,4])
result = np.tile(repeat_elements,2)
print(result)

[1 2 3 4 1 2 3 4]


In [88]:
#Q18.3: Repeat a 2D array using np.tile()
repeat_elements = np.array([1,2,3,4])
result = np.tile(repeat_elements,(2,3))
print(f"original array : {repeat_elements}")
print(f"result : \n{result}")

original array : [1 2 3 4]
result : 
[[1 2 3 4 1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4 1 2 3 4]]


In [89]:
#Q18.4: Create a pattern using np.tile()
pattern = np.array([1,0])
result = np.tile(pattern,5)
print(result)

[1 0 1 0 1 0 1 0 1 0]


In [90]:
#Q18.5: Repeat elements with different counts using np.repeat()
elements = np.array([1,2,3,4])
repeats = ([1,2,3,4])
result = np.repeat(elements , repeats)
print(result)

[1 2 2 3 3 3 4 4 4 4]


### Array Comparison and Logical Operations

In [91]:
#Q19.1: Compare two arrays for equality using np.array_equal()
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
arr3 =np.array([1,2,4])
print(f"Array :{arr1}")
print(f"Array :{arr2}")
print(f"Array :{arr3}")
print(f"A equals B: {np.array_equal(arr1, arr2)}")
print(f"A equals C: {np.array_equal(arr1, arr3)}")

Array :[1 2 3]
Array :[1 2 3]
Array :[1 2 4]
A equals B: True
A equals C: False


In [99]:
#Q19.2: Check if arrays are close using np.allclose()
a = np.array([1.0, 2.000001, 3.0])
b = np.array([1.0, 2.0, 3.0])
print(np.allclose(a, b))

True


In [101]:
#Q19.3: Apply logical AND operation between arrays
a = np.array([True, False, True])
b = np.array([False, False, True])
result = np.logical_and(a,b)
print(result)

[False False  True]


In [102]:
#Q19.4: Apply logical OR operation between arrays
a = np.array([True, False, True])
b = np.array([False, False, True])
result = np.logical_or(a,b)
print(result)

[ True False  True]


In [103]:
#Q19.5: Apply logical NOT operation to an array
a = np.array([True, False, True])
result = np.logical_not(a,b)
print(result)

[False  True False]


###  Array Set Operations

In [106]:
#Q20.1: Find unique elements in an array using np.unique()
a = np.array([1,2,2,3,3,3,4])
unique_element = np.unique(a)
print(f"Original array: {a}")
print(f"unique elements :{unique_element}")


Original array: [1 2 2 3 3 3 4]
unique elements :[1 2 3 4]


In [108]:
#Q20.2: Find the intersection of two arrays using np.intersect1d()
a = ([1,2,3,4])
b = ([2,4,5,6])
intersection = np.intersect1d(a,b)
print(f"Original array: {a,b}")
print(f"Intersection :{intersection}")


Original array: ([1, 2, 3, 4], [2, 4, 5, 6])
Intersection :[2 4]


In [109]:
#Q20.3: Find the union of two arrays using np.union1d()
a = ([1,2,3,4])
b = ([2,4,5,6])
union = np.union1d(a,b)
print(f"Original array: {a,b}")
print(f"union :{union}")

Original array: ([1, 2, 3, 4], [2, 4, 5, 6])
union :[1 2 3 4 5 6]


In [110]:
#Q20.4: Find elements in first array but not in second using np.setdiff1d()
a = ([1,2,3,4])
b = ([2,4,5,6])
set_difference =  np.setdiff1d(a,b)
print(f"Original array: {a,b}")
print(f"set difference :{set_difference}")

Original array: ([1, 2, 3, 4], [2, 4, 5, 6])
set difference :[1 3]


In [111]:
#Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
a = ([1,2,3,4])
b = ([2,4,5,6])
symmetric_difference = np.setxor1d(a,b)
print(f"Original array: {a,b}")
print(f"symmetric difference :{symmetric_difference}")

Original array: ([1, 2, 3, 4], [2, 4, 5, 6])
symmetric difference :[1 3 5 6]
